# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d45233a9cca38681456cb5521f290cf801c4e7d7375fb732762b9d6909f4d208748f6f91d76f77a80ab604004354bf622618e92b5e7fdfbe941ee1953ba7cbe

test:
  secret_key_base: 3405f363fea5e878bf0d58da49dd1280dfa4529a3a6b612bad397082900965e5016ace865e4d1c446be2a5beb5747bac114e8d8caae8eab4f278090b8b31566f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
